### ISSUE TITLE
Somebody can get operator permission issue

### ISSUE THREAD

**Issue by gal499605076** [lyokofirelyte/VariableTriggers#2]
I have done some trace in Player.setOp() call. It show below:

```
[16:22:29 WARN]: org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.setOp(CraftPlayer.java:260)
[16:22:29 WARN]: com.github.lyokofirelyte.VariableTriggers.VTParser.parse(VTParser.java:400)
[16:22:29 WARN]: com.github.lyokofirelyte.VariableTriggers.VTParser$1.run(VTParser.java:108)
[16:22:29 WARN]: java.lang.Thread.run(Thread.java:745)
[16:22:29 WARN]: DEBUG #233 Somebody try to get Op!
```

My script below:

```
Worlds:
- survival
Cooldown: 0
Cancelled: false
survival:
  2443,74,1082:
    Script:
    - '@CMDOP tppos -23333 74 -23333'
    - '@PAUSE 1'
    - '@SOUND CLICK <playerloc>'
    - '@PLAYER &7[&a传送系统&7]正在进行二次传送，请稍后...'
    - '@PLAYER &7[&a传送系统&7]按住shift即可取消本次传送'
    - '@PAUSE 1'
    - '@CALL issneak:is'
    Cooldown: 1
    ActiveCooldown: 1443687831213
  2443,74,1087:
    Script:
    - '@CMDOP tppos 4 69 -10'
    - '@PAUSE 1'
    - '@SOUND CLICK <playerloc>'
    - '@PLAYER &7[&a传送系统&7]正在进行二次传送，请稍后...'
    - '@PLAYER &7[&a传送系统&7]按住shift即可取消本次传送'
    - '@PAUSE 1'
    - '@CALL issneak:is'
    Cooldown: 1
    ActiveCooldown: 1443687833412
  2443,74,1092:
    Script:
    - '@CMDOP tppos 23333 85 23333'
    - '@PAUSE 1'
    - '@SOUND CLICK <playerloc>'
    - '@PLAYER &7[&a传送系统&7]正在进行二次传送，请稍后...'
    - '@PLAYER &7[&a传送系统&7]按住shift即可取消本次传送'
    - '@PAUSE 1'
    - '@CALL issneak:is'
main:
- '@COMMAND'
```

```
tpr.script.yml

Scripts:
  tp3:
    Script:
    - '@SOUND CLICK <playerloc>'
    - '@PLAYER &7[&a传送系统&7]&a倒计时&e 3'
    - '@PAUSE 1'
    - '@IF b <issneaking> = true'
    - '@PLAYER &7[&a传送系统&7]&c您已经取消传送'
    - '@ELSE'
    - '@CALL tpr:tp2'
    - '@ENDIF'
  tp2:
    Script:
    - '@SOUND CLICK <playerloc>'
    - '@PLAYER &7[&a传送系统&7]&a倒计时&e 2'
    - '@PAUSE 1'
    - '@IF b <issneaking> = true'
    - '@PLAYER &7[&a传送系统&7]&c您已经取消传送'
    - '@ELSE'
    - '@CALL tpr:tp1'
    - '@ENDIF'
  tp1:
    Script:
    - '@SOUND CLICK <playerloc>'
    - '@PLAYER &7[&a传送系统&7]&a倒计时&e 1'
    - '@IF b <issneaking> = true'
    - '@PLAYER &7[&a传送系统&7]&c您已经取消传送'
    - '@ELSE'
    - '@CALL tpr:end'
    - '@ENDIF'
  end:
    Script:
    - '@IF b <issneaking> = true'
    - '@PLAYER &7[&a传送系统&7]&c您已经取消传送'
    - '@ELSE'
    - '@PAUSE 1'
    - '@CMD rtp'
    - '@PAUSE 2'
    - '@SOUND ANVIL_USE <playerloc>'
    - '@PLAYER &7[&a传送系统&7]&a传送完成，祝您旅途愉快!'
    - '@ENDIF'


```

```
issneak.script.yml

Scripts:
  is:
    Script:
    - '@IF b <issneaking> = true'
    - '@PLAYER &7[&a传送系统&7]&c您已经取消传送'
    - '@ELSE'
    - '@CALL tpr:tp3'
    - '@ENDIF'


```

What's wrong on my script?
