### ISSUE TITLE
Bad PlayerHoldItem event

### ISSUE THREAD

**Issue by CorbyO** [lyokofirelyte/VariableTriggers#4]
Get the previous item information, not the current one.

```yml
# PlayerFoldItem.yml
Worlds:
- world
- world_nether
- world_the_end
Cooldown: 0
Cancelled: false
main:
- '@PLAYER <holdingitem:<playername>:egg>, <helditemname>'
```

![image](https://github.com/lyokofirelyte/VariableTriggers/assets/17669733/fae03f89-0d04-4887-a714-878cd0222708)

![image](https://github.com/lyokofirelyte/VariableTriggers/assets/17669733/9c9e7429-53ed-4607-bddf-1f151636bbb5)
